model_params:
  weights_path: "./frodo_ckpts/traversability_model_trace_frozendinov2_nocfs.pt"
  static_output_dim: 64
  modality: "monocular"
map_params:
  resolution: 0.1
  height: 19.2
  width: 19.2
  origin_x: 9.6
  origin_y: 9.6
  # map_to_world: [0.0, 5.0, -2.0]
  map_to_base_link: [0.0, 0.0, 0.0] # Note we denote world=base_link
input_topics:
  - type: image
    camera_id: "front_camera"
    image_topic: "/front_camera/compressed"
    info_topic: "/front_camera/camera_infos"
    target_shape: [288, 512]  # Example: resize input image to this size
    ds_factor: [0.5, 0.125] # Input downsample factor, Output downsample factor
    tf_frames: ["base_link", "front_optical"] # src -> target
    queue_size: 3
  - type: image
    camera_id: "rear_camera"
    image_topic: "/rear_camera/compressed"
    info_topic: "/rear_camera/camera_infos"
    target_shape: [360, 540]
    ds_factor: [1.0, 0.25]
    tf_frames: ["base_link", rear_optical]
    queue_size: 3
stale_cutoff_ms: 0.0 # Remove all messages older than this time, <=0.0 for no cutoff 
sync_cutoff_ms: 1000.0 # Time to wait for all sensors to be synced

output_topics:
  - type: depth
    key: "front_camera/depth_preds_metric"
    topic_name: "/creste/front_camera/depth"
  - type: depth
    key: "rear_camera/depth_preds_metric"
    topic_name: "/creste/rear_camera/depth"
  - type: traversability
    key: "traversability_cost"
    topic_name: "/creste/bev/traversability"
  # - type: debug
  #   topic_name: "/creste/semantic_elevation"

viz_params:
  history_window: 3
  viz_3d: False
